[2022-09-26T20:06:36.481-0300] {processor.py:156} INFO - Started process (PID=4994) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:06:36.481-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:06:36.482-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:06:36.481-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:06:36.493-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:06:36.493-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:06:36.493-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:06:36.493-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:06:36.494-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:06:36.499-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2022-09-26T20:07:12.847-0300] {processor.py:156} INFO - Started process (PID=5042) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:07:12.848-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:07:12.849-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:07:12.849-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:07:12.861-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:07:12.860-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:07:12.861-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:07:12.861-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:07:12.861-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:07:12.868-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-09-26T20:07:47.399-0300] {processor.py:156} INFO - Started process (PID=5078) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:07:47.400-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:07:47.401-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:07:47.401-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:07:47.414-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:07:47.413-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:07:47.414-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:07:47.414-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:07:47.414-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:07:47.422-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2022-09-26T20:08:22.369-0300] {processor.py:156} INFO - Started process (PID=5354) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:08:22.369-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:08:22.370-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:08:22.370-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:08:22.383-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:08:22.382-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:08:22.383-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:08:22.383-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:08:22.383-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:08:22.391-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2022-09-26T20:08:57.436-0300] {processor.py:156} INFO - Started process (PID=5390) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:08:57.437-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:08:57.437-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:08:57.437-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:08:57.450-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:08:57.449-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:08:57.450-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:08:57.450-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:08:57.450-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:08:57.456-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-09-26T20:09:32.369-0300] {processor.py:156} INFO - Started process (PID=5581) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:09:32.370-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:09:32.371-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:09:32.371-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:09:32.383-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:09:32.383-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:09:32.383-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:09:32.383-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:09:32.383-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:09:32.389-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-09-26T20:10:07.558-0300] {processor.py:156} INFO - Started process (PID=5668) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:10:07.559-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:10:07.559-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:10:07.559-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:10:07.571-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:10:07.571-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:10:07.571-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:10:07.571-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:10:07.572-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:10:07.578-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-09-26T20:10:43.585-0300] {processor.py:156} INFO - Started process (PID=5705) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:10:43.586-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:10:43.587-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:10:43.586-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:10:43.599-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:10:43.599-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:10:43.600-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:10:43.600-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:10:43.600-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:10:43.606-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2022-09-26T20:11:17.557-0300] {processor.py:156} INFO - Started process (PID=5792) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:11:17.557-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:11:17.558-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:11:17.558-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:11:17.572-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:11:17.572-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:11:17.572-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:11:17.572-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:11:17.572-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:11:17.578-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2022-09-26T20:11:54.908-0300] {processor.py:156} INFO - Started process (PID=5830) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:11:54.909-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:11:54.909-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:11:54.909-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:11:54.922-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:11:54.921-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:11:54.922-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:11:54.922-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:11:54.922-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:11:54.928-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2022-09-26T20:12:29.522-0300] {processor.py:156} INFO - Started process (PID=5865) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:12:29.523-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:12:29.524-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:12:29.523-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:12:29.535-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:12:29.535-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:12:29.536-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:12:29.536-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:12:29.536-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:12:29.542-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-09-26T20:13:04.436-0300] {processor.py:156} INFO - Started process (PID=5901) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:13:04.437-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:13:04.438-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:13:04.438-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:13:04.450-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:13:04.449-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:13:04.450-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:13:04.450-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:13:04.450-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:13:04.456-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-09-26T20:13:41.659-0300] {processor.py:156} INFO - Started process (PID=5939) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:13:41.659-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:13:41.660-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:13:41.660-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:13:41.672-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:13:41.672-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:13:41.672-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:13:41.672-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:13:41.673-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:13:41.679-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-09-26T20:14:16.806-0300] {processor.py:156} INFO - Started process (PID=5976) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:14:16.807-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:14:16.807-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:14:16.807-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:14:16.819-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:14:16.819-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:14:16.819-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:14:16.819-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:14:16.819-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:14:16.826-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-09-26T20:14:53.747-0300] {processor.py:156} INFO - Started process (PID=6013) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:14:53.748-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:14:53.748-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:14:53.748-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:14:53.760-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:14:53.760-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:14:53.760-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:14:53.760-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:14:53.761-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:14:53.767-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2022-09-26T20:15:27.339-0300] {processor.py:156} INFO - Started process (PID=6049) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:15:27.340-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:15:27.340-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:15:27.340-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:15:27.353-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:15:27.352-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:15:27.353-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:15:27.353-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:15:27.353-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:15:27.359-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-09-26T20:16:01.830-0300] {processor.py:156} INFO - Started process (PID=6238) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:16:01.831-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:16:01.832-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:16:01.832-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:16:01.845-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:16:01.845-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:16:01.846-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:16:01.846-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:16:01.846-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:16:01.854-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2022-09-26T20:16:36.653-0300] {processor.py:156} INFO - Started process (PID=6428) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:16:36.654-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:16:36.654-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:16:36.654-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:16:36.667-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:16:36.666-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:16:36.667-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:16:36.667-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:16:36.667-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:16:36.673-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-09-26T20:17:21.084-0300] {processor.py:156} INFO - Started process (PID=6879) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:17:21.085-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:17:21.085-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:17:21.085-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:17:21.097-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:17:21.097-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:17:21.097-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:17:21.097-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:17:21.097-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:17:21.104-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-09-26T20:17:56.504-0300] {processor.py:156} INFO - Started process (PID=7172) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:17:56.505-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:17:56.506-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:17:56.506-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:17:56.518-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:17:56.518-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:17:56.518-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:17:56.518-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:17:56.519-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:17:56.525-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2022-09-26T20:18:32.841-0300] {processor.py:156} INFO - Started process (PID=7210) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:18:32.842-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:18:32.842-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:18:32.842-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:18:32.855-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:18:32.855-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:18:32.856-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:18:32.856-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:18:32.856-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:18:32.862-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2022-09-26T20:19:06.128-0300] {processor.py:156} INFO - Started process (PID=7346) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:19:06.129-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:19:06.129-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:19:06.129-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:19:06.142-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:19:06.141-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:19:06.142-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:19:06.142-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:19:06.142-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:19:06.148-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-09-26T20:19:43.255-0300] {processor.py:156} INFO - Started process (PID=7384) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:19:43.256-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:19:43.256-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:19:43.256-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:19:43.269-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:19:43.268-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:19:43.269-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:19:43.269-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:19:43.269-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:19:43.275-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-09-26T20:20:18.078-0300] {processor.py:156} INFO - Started process (PID=7422) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:20:18.079-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:20:18.079-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:20:18.079-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:20:18.091-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:20:18.090-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:20:18.091-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:20:18.091-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:20:18.091-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:20:18.097-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2022-09-26T20:20:52.055-0300] {processor.py:156} INFO - Started process (PID=7480) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:20:52.056-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:20:52.057-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:20:52.057-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:20:52.069-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:20:52.068-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:20:52.069-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:20:52.069-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:20:52.069-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:20:52.075-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-09-26T20:21:26.245-0300] {processor.py:156} INFO - Started process (PID=7649) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:21:26.246-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:21:26.246-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:21:26.246-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:21:26.258-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:21:26.257-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:21:26.258-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:21:26.258-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:21:26.258-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:21:26.264-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2022-09-26T20:22:03.427-0300] {processor.py:156} INFO - Started process (PID=7685) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:22:03.428-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:22:03.428-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:22:03.428-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:22:03.440-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:22:03.440-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:22:03.440-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:22:03.440-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:22:03.440-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:22:03.446-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2022-09-26T20:22:36.039-0300] {processor.py:156} INFO - Started process (PID=7722) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:22:36.039-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:22:36.040-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:22:36.040-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:22:36.052-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:22:36.051-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:22:36.052-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:22:36.052-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:22:36.052-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:22:36.058-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-09-26T20:23:12.030-0300] {processor.py:156} INFO - Started process (PID=7759) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:23:12.031-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:23:12.031-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:23:12.031-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:23:12.044-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:23:12.043-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:23:12.044-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:23:12.044-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:23:12.044-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:23:12.050-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-09-26T20:23:46.837-0300] {processor.py:156} INFO - Started process (PID=7795) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:23:46.838-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:23:46.839-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:23:46.839-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:23:46.851-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:23:46.850-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:23:46.851-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:23:46.851-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:23:46.851-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:23:46.857-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-09-26T20:24:21.775-0300] {processor.py:156} INFO - Started process (PID=7832) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:24:21.776-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:24:21.777-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:24:21.776-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:24:21.789-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:24:21.788-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:24:21.789-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:24:21.789-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:24:21.789-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:24:21.796-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2022-09-26T20:25:00.196-0300] {processor.py:156} INFO - Started process (PID=7870) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:25:00.196-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:25:00.197-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:25:00.197-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:25:00.209-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:25:00.208-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:25:00.209-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:25:00.209-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:25:00.209-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:25:00.215-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2022-09-26T20:25:34.618-0300] {processor.py:156} INFO - Started process (PID=7906) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:25:34.619-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:25:34.619-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:25:34.619-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:25:34.631-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:25:34.631-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:25:34.631-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:25:34.631-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:25:34.632-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:25:34.638-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2022-09-26T20:26:12.480-0300] {processor.py:156} INFO - Started process (PID=7944) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:26:12.481-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:26:12.481-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:26:12.481-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:26:12.493-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:26:12.492-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:26:12.493-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:26:12.493-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:26:12.493-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:26:12.499-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2022-09-26T20:26:49.293-0300] {processor.py:156} INFO - Started process (PID=8032) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:26:49.294-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:26:49.295-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:26:49.295-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:26:49.307-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:26:49.306-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:26:49.307-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:26:49.307-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:26:49.307-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:26:49.313-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-09-26T20:27:24.727-0300] {processor.py:156} INFO - Started process (PID=8069) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:27:24.728-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:27:24.729-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:27:24.728-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:27:24.741-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:27:24.741-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:27:24.741-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:27:24.741-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:27:24.741-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:27:24.747-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-09-26T20:28:00.121-0300] {processor.py:156} INFO - Started process (PID=8106) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:28:00.122-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:28:00.122-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:28:00.122-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:28:00.134-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:28:00.134-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:28:00.134-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:28:00.134-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:28:00.134-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:28:00.140-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-09-26T20:28:33.929-0300] {processor.py:156} INFO - Started process (PID=8141) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:28:33.929-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:28:33.930-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:28:33.930-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:28:33.942-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:28:33.942-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:28:33.943-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:28:33.943-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:28:33.943-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:28:33.949-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-09-26T20:29:12.088-0300] {processor.py:156} INFO - Started process (PID=8180) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:29:12.089-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:29:12.090-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:29:12.090-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:29:12.102-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:29:12.102-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:29:12.102-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:29:12.102-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:29:12.102-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:29:12.108-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-09-26T20:29:49.112-0300] {processor.py:156} INFO - Started process (PID=8218) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:29:49.113-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:29:49.113-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:29:49.113-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:29:49.127-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:29:49.126-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:29:49.127-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:29:49.127-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:29:49.127-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:29:49.133-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2022-09-26T20:30:22.920-0300] {processor.py:156} INFO - Started process (PID=8253) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:30:22.921-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:30:22.921-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:30:22.921-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:30:22.933-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:30:22.933-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:30:22.934-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:30:22.934-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:30:22.934-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:30:22.940-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-09-26T20:31:00.973-0300] {processor.py:156} INFO - Started process (PID=8292) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:31:00.975-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:31:00.975-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:31:00.975-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:31:00.987-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:31:00.986-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:31:00.987-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:31:00.987-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:31:00.987-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:31:00.993-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-09-26T20:31:36.246-0300] {processor.py:156} INFO - Started process (PID=8379) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:31:36.247-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:31:36.247-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:31:36.247-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:31:36.259-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:31:36.258-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:31:36.259-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:31:36.259-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:31:36.259-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:31:36.265-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2022-09-26T20:32:13.381-0300] {processor.py:156} INFO - Started process (PID=8418) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:32:13.382-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:32:13.383-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:32:13.383-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:32:13.395-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:32:13.395-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:32:13.395-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:32:13.395-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:32:13.395-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:32:13.401-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-09-26T20:32:52.334-0300] {processor.py:156} INFO - Started process (PID=8457) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:32:52.335-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:32:52.336-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:32:52.336-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:32:52.348-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:32:52.348-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:32:52.348-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:32:52.348-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:32:52.348-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:32:52.355-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2022-09-26T20:33:26.418-0300] {processor.py:156} INFO - Started process (PID=8495) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:33:26.419-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:33:26.420-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:33:26.420-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:33:26.431-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:33:26.431-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:33:26.432-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:33:26.432-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:33:26.432-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:33:26.438-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2022-09-26T20:34:03.365-0300] {processor.py:156} INFO - Started process (PID=8531) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:34:03.366-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:34:03.366-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:34:03.366-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:34:03.379-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:34:03.378-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:34:03.379-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:34:03.379-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:34:03.379-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:34:03.385-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2022-09-26T20:34:40.242-0300] {processor.py:156} INFO - Started process (PID=8569) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:34:40.243-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:34:40.244-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:34:40.243-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:34:40.255-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:34:40.255-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:34:40.255-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:34:40.255-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:34:40.256-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:34:40.261-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2022-09-26T20:35:15.203-0300] {processor.py:156} INFO - Started process (PID=8606) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:35:15.203-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:35:15.204-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:35:15.204-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:35:15.216-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:35:15.215-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:35:15.216-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:35:15.216-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:35:15.216-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:35:15.222-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2022-09-26T20:35:48.761-0300] {processor.py:156} INFO - Started process (PID=8641) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:35:48.762-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:35:48.762-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:35:48.762-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:35:48.775-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:35:48.774-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:35:48.775-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:35:48.775-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:35:48.775-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:35:48.781-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-09-26T20:36:23.160-0300] {processor.py:156} INFO - Started process (PID=8731) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:36:23.161-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:36:23.161-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:36:23.161-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:36:23.173-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:36:23.173-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:36:23.174-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:36:23.173-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:36:23.174-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:36:23.180-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-09-26T20:36:59.393-0300] {processor.py:156} INFO - Started process (PID=8767) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:36:59.394-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:36:59.395-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:36:59.395-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:36:59.407-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:36:59.406-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:36:59.407-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:36:59.407-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:36:59.407-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:36:59.413-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-09-26T20:37:32.994-0300] {processor.py:156} INFO - Started process (PID=8802) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:37:32.995-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:37:32.996-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:37:32.995-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:37:33.008-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:37:33.007-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:37:33.008-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:37:33.008-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:37:33.008-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:37:33.015-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2022-09-26T20:38:08.467-0300] {processor.py:156} INFO - Started process (PID=8837) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:38:08.468-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:38:08.469-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:38:08.469-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:38:08.482-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:38:08.481-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:38:08.482-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:38:08.482-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:38:08.482-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:38:08.489-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2022-09-26T20:38:41.603-0300] {processor.py:156} INFO - Started process (PID=8873) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:38:41.604-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:38:41.605-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:38:41.604-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:38:41.617-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:38:41.617-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:38:41.617-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:38:41.617-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:38:41.618-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:38:41.624-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-09-26T20:39:17.022-0300] {processor.py:156} INFO - Started process (PID=8909) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:39:17.023-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:39:17.024-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:39:17.024-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:39:17.037-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:39:17.036-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:39:17.037-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:39:17.037-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:39:17.037-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:39:17.043-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2022-09-26T20:39:51.580-0300] {processor.py:156} INFO - Started process (PID=8946) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:39:51.581-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:39:51.581-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:39:51.581-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:39:51.595-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:39:51.594-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:39:51.595-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:39:51.595-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:39:51.595-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:39:51.601-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2022-09-26T20:40:27.685-0300] {processor.py:156} INFO - Started process (PID=8982) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:40:27.686-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:40:27.686-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:40:27.686-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:40:27.699-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:40:27.698-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:40:27.699-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:40:27.699-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:40:27.699-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:40:27.705-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-09-26T20:41:01.097-0300] {processor.py:156} INFO - Started process (PID=9018) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:41:01.099-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:41:01.099-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:41:01.099-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:41:01.113-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:41:01.112-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:41:01.113-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:41:01.113-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:41:01.113-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:41:01.119-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2022-09-26T20:41:39.264-0300] {processor.py:156} INFO - Started process (PID=9108) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:41:39.265-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:41:39.265-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:41:39.265-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:41:39.278-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:41:39.277-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:41:39.278-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:41:39.278-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:41:39.278-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:41:39.284-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-09-26T20:42:18.502-0300] {processor.py:156} INFO - Started process (PID=9148) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:42:18.503-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:42:18.503-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:42:18.503-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:42:18.515-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:42:18.515-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:42:18.516-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:42:18.515-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:42:18.516-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:42:18.522-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2022-09-26T20:42:57.289-0300] {processor.py:156} INFO - Started process (PID=9187) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:42:57.290-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:42:57.290-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:42:57.290-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:42:57.303-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:42:57.303-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:42:57.303-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:42:57.303-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:42:57.303-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:42:57.310-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2022-09-26T20:43:33.152-0300] {processor.py:156} INFO - Started process (PID=9223) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:43:33.153-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:43:33.153-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:43:33.153-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:43:33.166-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:43:33.165-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:43:33.166-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:43:33.166-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:43:33.166-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:43:33.172-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-09-26T20:44:08.423-0300] {processor.py:156} INFO - Started process (PID=9259) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:44:08.423-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:44:08.424-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:44:08.424-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:44:08.437-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:44:08.437-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:44:08.437-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:44:08.437-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:44:08.437-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:44:08.445-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2022-09-26T20:44:46.371-0300] {processor.py:156} INFO - Started process (PID=9297) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:44:46.372-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:44:46.373-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:44:46.373-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:44:46.386-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:44:46.385-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:44:46.386-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:44:46.386-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:44:46.386-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:44:46.393-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2022-09-26T20:45:22.425-0300] {processor.py:156} INFO - Started process (PID=9335) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:45:22.426-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:45:22.427-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:45:22.427-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:45:22.439-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:45:22.439-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:45:22.439-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:45:22.439-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:45:22.439-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:45:22.446-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2022-09-26T20:45:55.282-0300] {processor.py:156} INFO - Started process (PID=9370) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:45:55.283-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:45:55.283-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:45:55.283-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:45:55.296-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:45:55.296-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:45:55.296-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:45:55.296-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:45:55.297-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:45:55.303-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2022-09-26T20:46:30.434-0300] {processor.py:156} INFO - Started process (PID=9455) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:46:30.435-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:46:30.436-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:46:30.436-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:46:30.448-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:46:30.448-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:46:30.449-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:46:30.449-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:46:30.449-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:46:30.455-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2022-09-26T20:47:04.260-0300] {processor.py:156} INFO - Started process (PID=9491) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:47:04.261-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:47:04.262-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:47:04.262-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:47:04.276-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:47:04.276-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:47:04.277-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:47:04.277-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:47:04.277-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:47:04.283-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2022-09-26T20:47:42.652-0300] {processor.py:156} INFO - Started process (PID=9529) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:47:42.653-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:47:42.653-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:47:42.653-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:47:42.666-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:47:42.666-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:47:42.666-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:47:42.666-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:47:42.666-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:47:42.673-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2022-09-26T20:48:19.592-0300] {processor.py:156} INFO - Started process (PID=9567) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:48:19.594-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:48:19.594-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:48:19.594-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:48:19.607-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:48:19.606-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:48:19.607-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:48:19.607-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:48:19.607-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:48:19.616-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2022-09-26T20:48:53.801-0300] {processor.py:156} INFO - Started process (PID=9603) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:48:53.802-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:48:53.803-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:48:53.803-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:48:53.818-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:48:53.817-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:48:53.818-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:48:53.818-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:48:53.818-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:48:53.827-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2022-09-26T20:49:28.127-0300] {processor.py:156} INFO - Started process (PID=9637) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:49:28.128-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:49:28.129-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:49:28.129-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:49:28.141-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:49:28.141-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:49:28.142-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:49:28.142-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:49:28.142-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:49:28.148-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2022-09-26T20:50:02.067-0300] {processor.py:156} INFO - Started process (PID=9673) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:50:02.067-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:50:02.068-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:50:02.068-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:50:02.081-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:50:02.080-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:50:02.081-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:50:02.081-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:50:02.081-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:50:02.087-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2022-09-26T20:50:39.593-0300] {processor.py:156} INFO - Started process (PID=9711) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:50:39.593-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:50:39.594-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:50:39.594-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:50:39.606-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:50:39.606-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:50:39.606-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:50:39.606-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:50:39.607-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:50:39.613-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2022-09-26T20:51:13.316-0300] {processor.py:156} INFO - Started process (PID=9747) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:51:13.317-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:51:13.317-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:51:13.317-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:51:13.329-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:51:13.329-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:51:13.330-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:51:13.330-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:51:13.330-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:51:13.336-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-09-26T20:51:47.978-0300] {processor.py:156} INFO - Started process (PID=9836) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:51:47.979-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:51:47.980-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:51:47.980-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:51:47.992-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:51:47.992-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:51:47.993-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:51:47.992-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:51:47.993-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:51:47.999-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-09-26T20:52:22.055-0300] {processor.py:156} INFO - Started process (PID=9871) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:52:22.056-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:52:22.056-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:52:22.056-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:52:22.070-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:52:22.069-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:52:22.070-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:52:22.070-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:52:22.070-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:52:22.077-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2022-09-26T20:53:01.704-0300] {processor.py:156} INFO - Started process (PID=9910) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:53:01.705-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:53:01.706-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:53:01.706-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:53:01.720-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:53:01.719-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:53:01.720-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:53:01.720-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:53:01.720-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:53:01.727-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2022-09-26T20:53:37.289-0300] {processor.py:156} INFO - Started process (PID=9947) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:53:37.290-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:53:37.290-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:53:37.290-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:53:37.302-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:53:37.302-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:53:37.302-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:53:37.302-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:53:37.303-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:53:37.308-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2022-09-26T20:54:15.015-0300] {processor.py:156} INFO - Started process (PID=9985) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:54:15.017-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:54:15.018-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:54:15.018-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:54:15.032-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:54:15.030-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:54:15.032-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:54:15.032-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:54:15.032-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:54:15.038-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2022-09-26T20:54:50.536-0300] {processor.py:156} INFO - Started process (PID=10021) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:54:50.537-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:54:50.537-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:54:50.537-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:54:50.551-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:54:50.550-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:54:50.551-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:54:50.551-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:54:50.551-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:54:50.557-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2022-09-26T20:55:28.926-0300] {processor.py:156} INFO - Started process (PID=10060) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:55:28.927-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:55:28.928-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:55:28.928-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:55:28.941-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:55:28.940-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:55:28.942-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:55:28.942-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:55:28.942-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:55:28.949-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2022-09-26T20:56:08.021-0300] {processor.py:156} INFO - Started process (PID=10099) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:56:08.022-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:56:08.023-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:56:08.023-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:56:08.035-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:56:08.034-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:56:08.035-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:56:08.035-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:56:08.035-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:56:08.043-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2022-09-26T20:56:46.170-0300] {processor.py:156} INFO - Started process (PID=10190) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:56:46.171-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:56:46.171-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:56:46.171-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:56:46.184-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:56:46.184-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:56:46.185-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:56:46.184-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:56:46.185-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:56:46.191-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2022-09-26T20:57:21.686-0300] {processor.py:156} INFO - Started process (PID=10226) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:57:21.687-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:57:21.688-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:57:21.688-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:57:21.700-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:57:21.700-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:57:21.700-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:57:21.700-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:57:21.701-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:57:21.708-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2022-09-26T20:57:55.857-0300] {processor.py:156} INFO - Started process (PID=10262) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:57:55.858-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:57:55.858-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:57:55.858-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:57:55.872-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:57:55.871-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:57:55.872-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:57:55.872-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:57:55.872-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:57:55.878-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2022-09-26T20:58:31.107-0300] {processor.py:156} INFO - Started process (PID=10298) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:58:31.108-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:58:31.108-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:58:31.108-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:58:31.121-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:58:31.121-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:58:31.122-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:58:31.121-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:58:31.122-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:58:31.129-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2022-09-26T20:59:05.943-0300] {processor.py:156} INFO - Started process (PID=10332) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:59:05.944-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:59:05.945-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:59:05.945-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:59:05.958-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:59:05.958-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:59:05.958-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:59:05.958-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:59:05.959-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:59:05.965-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2022-09-26T20:59:41.033-0300] {processor.py:156} INFO - Started process (PID=10368) to work on /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:59:41.034-0300] {processor.py:758} INFO - Processing file /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-09-26T20:59:41.035-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:59:41.035-0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:59:41.047-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:59:41.046-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-09-26T20:59:41.047-0300] {logging_mixin.py:117} INFO - [2022-09-26T20:59:41.047-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-09-26T20:59:41.047-0300] {processor.py:770} WARNING - No viable dags retrieved from /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-09-26T20:59:41.053-0300] {processor.py:178} INFO - Processing /home/nicholasbaraldi/.pyenv/versions/3.10.4/envs/twitter-api-data-stack-venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
