[2022-10-01T01:44:54.866+0000] {processor.py:156} INFO - Started process (PID=1857) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:44:54.866+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:44:54.866+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:44:54.866+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:44:54.867+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:44:54.875+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.011 seconds
[2022-10-01T01:45:25.185+0000] {processor.py:156} INFO - Started process (PID=1921) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:45:25.186+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:45:25.186+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:45:25.186+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:45:25.187+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:45:25.195+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.012 seconds
[2022-10-01T01:45:55.438+0000] {processor.py:156} INFO - Started process (PID=1985) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:45:55.475+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:45:55.476+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:45:55.476+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:45:55.477+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:45:55.486+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.050 seconds
[2022-10-01T01:46:26.423+0000] {processor.py:156} INFO - Started process (PID=2050) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:46:26.424+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:46:26.424+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:46:26.424+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:46:26.425+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:46:26.433+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.011 seconds
[2022-10-01T01:46:56.454+0000] {processor.py:156} INFO - Started process (PID=2105) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:46:56.455+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:46:56.455+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:46:56.455+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:46:56.456+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:46:56.465+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.012 seconds
[2022-10-01T01:47:26.651+0000] {processor.py:156} INFO - Started process (PID=2169) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:47:26.651+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:47:26.652+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:47:26.652+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:47:26.653+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:47:26.660+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.011 seconds
[2022-10-01T01:47:57.446+0000] {processor.py:156} INFO - Started process (PID=2233) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:47:57.447+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:47:57.447+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:47:57.447+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:47:57.448+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:47:57.456+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.011 seconds
[2022-10-01T01:48:28.405+0000] {processor.py:156} INFO - Started process (PID=2297) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:48:28.405+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:48:28.406+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:48:28.406+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:48:28.407+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:48:28.415+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.011 seconds
[2022-10-01T01:48:58.472+0000] {processor.py:156} INFO - Started process (PID=2352) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:48:58.473+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:48:58.474+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:48:58.474+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:48:58.474+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:48:58.483+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.012 seconds
[2022-10-01T01:49:29.493+0000] {processor.py:156} INFO - Started process (PID=2416) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:49:29.493+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:49:29.493+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:49:29.493+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:49:29.494+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:49:29.502+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.011 seconds
[2022-10-01T01:49:59.607+0000] {processor.py:156} INFO - Started process (PID=2481) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:49:59.608+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:49:59.608+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:49:59.608+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:49:59.609+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:49:59.617+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.012 seconds
[2022-10-01T01:50:29.770+0000] {processor.py:156} INFO - Started process (PID=2546) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:50:29.770+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:50:29.771+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:50:29.771+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:50:29.771+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:50:29.779+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.011 seconds
[2022-10-01T01:51:00.696+0000] {processor.py:156} INFO - Started process (PID=2601) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:51:00.697+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:51:00.697+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:51:00.697+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:51:00.698+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:51:00.711+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.018 seconds
[2022-10-01T01:51:31.492+0000] {processor.py:156} INFO - Started process (PID=2665) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:51:31.492+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:51:31.492+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:51:31.492+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:51:31.493+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:51:31.502+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.012 seconds
[2022-10-01T01:52:01.574+0000] {processor.py:156} INFO - Started process (PID=2729) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:52:01.611+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:52:01.611+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:52:01.611+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:52:01.612+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:52:01.620+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.048 seconds
[2022-10-01T01:52:31.724+0000] {processor.py:156} INFO - Started process (PID=2794) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:52:31.724+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:52:31.724+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:52:31.724+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:52:31.725+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:52:31.733+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.011 seconds
[2022-10-01T01:53:02.675+0000] {processor.py:156} INFO - Started process (PID=2849) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:53:02.685+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:53:02.685+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:53:02.685+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:53:02.686+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:53:02.694+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.021 seconds
[2022-10-01T01:53:33.554+0000] {processor.py:156} INFO - Started process (PID=2913) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:53:33.555+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:53:33.555+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:53:33.555+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:53:33.556+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:53:33.564+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.011 seconds
[2022-10-01T01:54:04.484+0000] {processor.py:156} INFO - Started process (PID=2977) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:54:04.485+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:54:04.485+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:54:04.485+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:54:04.486+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:54:04.494+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.011 seconds
[2022-10-01T01:54:34.565+0000] {processor.py:156} INFO - Started process (PID=3042) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:54:34.566+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:54:34.566+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:54:34.566+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:54:34.567+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:54:34.576+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.012 seconds
[2022-10-01T01:55:05.512+0000] {processor.py:156} INFO - Started process (PID=3106) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:55:05.513+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:55:05.513+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:55:05.513+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:55:05.514+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:55:05.522+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.011 seconds
[2022-10-01T01:55:36.415+0000] {processor.py:156} INFO - Started process (PID=3161) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:55:36.415+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:55:36.415+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:55:36.415+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:55:36.416+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:55:36.424+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.013 seconds
[2022-10-01T01:56:07.247+0000] {processor.py:156} INFO - Started process (PID=3225) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:56:07.247+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:56:07.248+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:56:07.248+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:56:07.249+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:56:07.257+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.012 seconds
[2022-10-01T01:56:38.157+0000] {processor.py:156} INFO - Started process (PID=3289) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:56:38.157+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:56:38.157+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:56:38.157+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:56:38.158+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:56:38.165+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.010 seconds
[2022-10-01T01:57:09.121+0000] {processor.py:156} INFO - Started process (PID=3353) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:57:09.122+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:57:09.122+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:57:09.122+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:57:09.123+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:57:09.130+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.010 seconds
[2022-10-01T01:57:39.207+0000] {processor.py:156} INFO - Started process (PID=3408) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:57:39.207+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:57:39.207+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:57:39.207+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:57:39.208+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:57:39.216+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.011 seconds
[2022-10-01T01:58:09.483+0000] {processor.py:156} INFO - Started process (PID=3472) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:58:09.483+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:58:09.484+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:58:09.484+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:58:09.484+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:58:09.492+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.010 seconds
[2022-10-01T01:58:17.519+0000] {processor.py:156} INFO - Started process (PID=3482) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:58:17.519+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:58:17.519+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:58:17.519+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:58:17.520+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:58:17.520+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 4
    with DA
          ^
SyntaxError: invalid syntax
[2022-10-01T01:58:17.521+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:58:17.548+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.031 seconds
[2022-10-01T01:58:20.536+0000] {processor.py:156} INFO - Started process (PID=3483) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:58:20.536+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:58:20.537+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:58:20.537+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:58:20.538+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:58:20.537+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 4
    with DAG() as
                 ^
SyntaxError: invalid syntax
[2022-10-01T01:58:20.538+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:58:20.550+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.016 seconds
[2022-10-01T01:58:42.507+0000] {processor.py:156} INFO - Started process (PID=3538) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:58:42.508+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:58:42.508+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:58:42.508+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:58:42.509+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:58:42.509+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 4
    with DAG() as dag
                    ^
SyntaxError: invalid syntax
[2022-10-01T01:58:42.510+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:58:42.522+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.017 seconds
[2022-10-01T01:58:51.561+0000] {processor.py:156} INFO - Started process (PID=3548) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:58:51.561+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:58:51.562+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:58:51.562+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:58:51.563+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:58:51.562+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 4
    with DAG('twitter') as dag
                             ^
SyntaxError: invalid syntax
[2022-10-01T01:58:51.563+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:58:51.597+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.037 seconds
[2022-10-01T01:58:53.574+0000] {processor.py:156} INFO - Started process (PID=3549) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:58:53.575+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:58:53.575+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:58:53.575+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:58:53.576+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:58:53.576+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 4
    with DAG('t') as dag
                       ^
SyntaxError: invalid syntax
[2022-10-01T01:58:53.577+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:58:53.588+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.016 seconds
[2022-10-01T01:58:56.589+0000] {processor.py:156} INFO - Started process (PID=3550) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:58:56.589+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:58:56.589+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:58:56.589+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:58:56.590+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:58:56.590+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 4
    with DAG('ingest_twe') as dag
                                ^
SyntaxError: invalid syntax
[2022-10-01T01:58:56.591+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:58:56.624+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.037 seconds
[2022-10-01T01:58:59.645+0000] {processor.py:156} INFO - Started process (PID=3562) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:58:59.645+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:58:59.645+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:58:59.645+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:58:59.647+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:58:59.646+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 4
    with DAG('ingest_twitter') as dag
                                    ^
SyntaxError: invalid syntax
[2022-10-01T01:58:59.647+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:58:59.680+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.037 seconds
[2022-10-01T01:59:03.661+0000] {processor.py:156} INFO - Started process (PID=3563) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:03.662+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:59:03.662+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:59:03.662+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:03.663+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:59:03.663+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 4
    with DAG('ingest_twitter', sta) as dag
                                         ^
SyntaxError: invalid syntax
[2022-10-01T01:59:03.663+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:03.675+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.015 seconds
[2022-10-01T01:59:07.682+0000] {processor.py:156} INFO - Started process (PID=3564) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:07.682+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:59:07.682+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:59:07.682+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:07.683+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:59:07.683+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 4
    with DAG('ingest_twitter', start_date) as dag
                                                ^
SyntaxError: invalid syntax
[2022-10-01T01:59:07.684+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:07.696+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.016 seconds
[2022-10-01T01:59:10.560+0000] {processor.py:156} INFO - Started process (PID=3608) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:10.560+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:59:10.560+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:59:10.560+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:10.561+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:59:10.561+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 4
    with DAG('ingest_twitter', start_date()) as dag
                                                  ^
SyntaxError: invalid syntax
[2022-10-01T01:59:10.562+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:10.573+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.015 seconds
[2022-10-01T01:59:18.593+0000] {processor.py:156} INFO - Started process (PID=3609) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:18.630+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:59:18.631+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:59:18.631+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:18.632+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:59:18.632+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 2
    from date
            ^
SyntaxError: invalid syntax
[2022-10-01T01:59:18.632+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:18.644+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.053 seconds
[2022-10-01T01:59:19.609+0000] {processor.py:156} INFO - Started process (PID=3612) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:19.610+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:59:19.610+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:59:19.610+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:19.611+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:59:19.611+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 2
    from datetime
                ^
SyntaxError: invalid syntax
[2022-10-01T01:59:19.612+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:19.625+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.018 seconds
[2022-10-01T01:59:21.624+0000] {processor.py:156} INFO - Started process (PID=3620) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:21.624+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:59:21.624+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:59:21.624+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:21.625+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:59:21.625+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 2
    from datetime
                 ^
SyntaxError: invalid syntax
[2022-10-01T01:59:21.626+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:21.659+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.037 seconds
[2022-10-01T01:59:23.652+0000] {processor.py:156} INFO - Started process (PID=3621) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:23.652+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:59:23.653+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:59:23.652+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:23.654+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:59:23.653+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 2
    from datetime impor
                      ^
SyntaxError: invalid syntax
[2022-10-01T01:59:23.654+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:23.666+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.016 seconds
[2022-10-01T01:59:24.659+0000] {processor.py:156} INFO - Started process (PID=3622) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:24.659+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:59:24.659+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:59:24.659+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:24.660+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:59:24.660+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 2
    from datetime import
                       ^
SyntaxError: invalid syntax
[2022-10-01T01:59:24.661+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:24.694+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.037 seconds
[2022-10-01T01:59:28.702+0000] {processor.py:156} INFO - Started process (PID=3623) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:28.703+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:59:28.704+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:59:28.704+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:28.705+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:59:28.705+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 4
    with DAG('ingest_twitter', start_date()) as dag
                                                  ^
SyntaxError: invalid syntax
[2022-10-01T01:59:28.705+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:28.720+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.021 seconds
[2022-10-01T01:59:34.839+0000] {processor.py:156} INFO - Started process (PID=3635) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:34.839+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:59:34.840+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:59:34.840+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:34.841+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:59:34.840+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 4
    with DAG('ingest_twitter', start_date= datetime()) as dag
                                                            ^
SyntaxError: invalid syntax
[2022-10-01T01:59:34.841+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:34.858+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.021 seconds
[2022-10-01T01:59:36.852+0000] {processor.py:156} INFO - Started process (PID=3636) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:36.853+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:59:36.853+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:59:36.853+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:36.854+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:59:36.854+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 4
    with DAG('ingest_twitter', start_date= datetime(2022,)) as dag
                                                                 ^
SyntaxError: invalid syntax
[2022-10-01T01:59:36.854+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:36.866+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.015 seconds
[2022-10-01T01:59:38.863+0000] {processor.py:156} INFO - Started process (PID=3637) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:38.864+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:59:38.864+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:59:38.864+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:38.866+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:59:38.865+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 4
    with DAG('ingest_twitter', start_date= datetime(2022,09)) as dag
                                                          ^
SyntaxError: invalid token
[2022-10-01T01:59:38.866+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:38.882+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.020 seconds
[2022-10-01T01:59:40.842+0000] {processor.py:156} INFO - Started process (PID=3655) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:40.842+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:59:40.843+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:59:40.843+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:40.844+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:59:40.843+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 4
    with DAG('ingest_twitter', start_date= datetime(2022,09,30)) as dag
                                                          ^
SyntaxError: invalid token
[2022-10-01T01:59:40.844+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:40.856+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.015 seconds
[2022-10-01T01:59:51.635+0000] {processor.py:156} INFO - Started process (PID=3682) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:51.673+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:59:51.673+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:59:51.673+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:51.674+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:59:51.674+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 4
    with DAG('ingest_twitter', start_date= datetime(2022,09,30), ) as dag
                                                          ^
SyntaxError: invalid token
[2022-10-01T01:59:51.675+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:51.687+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.053 seconds
[2022-10-01T01:59:59.738+0000] {processor.py:156} INFO - Started process (PID=3692) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:59.738+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T01:59:59.739+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:59:59.738+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:59.740+0000] {logging_mixin.py:117} INFO - [2022-10-01T01:59:59.739+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 4
    with DAG('ingest_twitter', start_date = datetime(2022,09,30), ) as dag
                                                           ^
SyntaxError: invalid token
[2022-10-01T01:59:59.740+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T01:59:59.752+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.016 seconds
[2022-10-01T02:00:30.740+0000] {processor.py:156} INFO - Started process (PID=3756) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:00:30.741+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:00:30.741+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:00:30.741+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:00:30.742+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:00:30.742+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 4
    with DAG('ingest_twitter', start_date = datetime(2022,09,30), ) as dag
                                                           ^
SyntaxError: invalid token
[2022-10-01T02:00:30.743+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:00:30.756+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.018 seconds
[2022-10-01T02:00:40.874+0000] {processor.py:156} INFO - Started process (PID=3768) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:00:40.874+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:00:40.874+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:00:40.874+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:00:40.875+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:00:40.875+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 4
    with DAG('ingest_twitter', start_date = datetime(2022,09,30), ) as dag:
                                                           ^
SyntaxError: invalid token
[2022-10-01T02:00:40.876+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:00:40.887+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.015 seconds
[2022-10-01T02:00:51.713+0000] {processor.py:156} INFO - Started process (PID=3812) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:00:51.713+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:00:51.713+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:00:51.713+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:00:51.714+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:00:51.714+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 4
    with DAG('ingest_twitter', start_date = datetime(2022,09,30),schedule  ) as dag:
                                                           ^
SyntaxError: invalid token
[2022-10-01T02:00:51.715+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:00:51.748+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.037 seconds
[2022-10-01T02:00:52.723+0000] {processor.py:156} INFO - Started process (PID=3813) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:00:52.723+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:00:52.724+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:00:52.724+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:00:52.725+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:00:52.724+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 4
    with DAG('ingest_twitter', start_date = datetime(2022,09,30), schedule  ) as dag:
                                                           ^
SyntaxError: invalid token
[2022-10-01T02:00:52.725+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:00:52.737+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.016 seconds
[2022-10-01T02:00:55.737+0000] {processor.py:156} INFO - Started process (PID=3814) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:00:55.738+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:00:55.738+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:00:55.738+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:00:55.739+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:00:55.739+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 4
    with DAG('ingest_twitter', start_date = datetime(2022,09,30), schedule  _intercal) as dag:
                                                           ^
SyntaxError: invalid token
[2022-10-01T02:00:55.739+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:00:55.753+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.019 seconds
[2022-10-01T02:00:59.773+0000] {processor.py:156} INFO - Started process (PID=3824) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:00:59.774+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:00:59.775+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:00:59.775+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:00:59.776+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:00:59.776+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 4
    with DAG('ingest_twitter', start_date = datetime(2022,09,30), schedule_interval) as dag:
                                                           ^
SyntaxError: invalid token
[2022-10-01T02:00:59.777+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:00:59.809+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.038 seconds
[2022-10-01T02:01:09.858+0000] {processor.py:156} INFO - Started process (PID=3827) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:01:09.859+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:01:09.859+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:01:09.859+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:01:09.860+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:01:09.860+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 4
    with DAG('ingest_twitter', start_date = datetime(2022,09,30), schedule_interval = ) as dag:
                                                           ^
SyntaxError: invalid token
[2022-10-01T02:01:09.860+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:01:09.872+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.016 seconds
[2022-10-01T02:01:11.869+0000] {processor.py:156} INFO - Started process (PID=3837) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:01:11.869+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:01:11.870+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:01:11.869+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:01:11.871+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:01:11.870+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 4
    with DAG('ingest_twitter', start_date = datetime(2022,09,30), schedule_interval = '') as dag:
                                                           ^
SyntaxError: invalid token
[2022-10-01T02:01:11.871+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:01:11.904+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.037 seconds
[2022-10-01T02:01:41.923+0000] {processor.py:156} INFO - Started process (PID=3892) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:01:41.924+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:01:41.924+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:01:41.924+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:01:41.926+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:01:41.925+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 4
    with DAG('ingest_twitter', start_date = datetime(2022,09,30), schedule_interval = '') as dag:
                                                           ^
SyntaxError: invalid token
[2022-10-01T02:01:41.926+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:01:41.938+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.016 seconds
[2022-10-01T02:02:12.034+0000] {processor.py:156} INFO - Started process (PID=3957) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:02:12.034+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:02:12.034+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:02:12.034+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:02:12.035+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:02:12.035+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 4
    with DAG('ingest_twitter', start_date = datetime(2022,09,30), schedule_interval = '') as dag:
                                                           ^
SyntaxError: invalid token
[2022-10-01T02:02:12.036+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:02:12.063+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.031 seconds
[2022-10-01T02:02:42.944+0000] {processor.py:156} INFO - Started process (PID=4021) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:02:42.945+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:02:42.945+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:02:42.945+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:02:42.947+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:02:42.946+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 4
    with DAG('ingest_twitter', start_date = datetime(2022,09,30), schedule_interval = '') as dag:
                                                           ^
SyntaxError: invalid token
[2022-10-01T02:02:42.947+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:02:42.959+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.017 seconds
[2022-10-01T02:03:13.800+0000] {processor.py:156} INFO - Started process (PID=4085) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:03:13.801+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:03:13.801+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:03:13.801+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:03:13.802+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:03:13.802+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 4
    with DAG('ingest_twitter', start_date = datetime(2022,09,30), schedule_interval = '') as dag:
                                                           ^
SyntaxError: invalid token
[2022-10-01T02:03:13.803+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:03:13.816+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.018 seconds
[2022-10-01T02:03:43.903+0000] {processor.py:156} INFO - Started process (PID=4140) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:03:43.904+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:03:43.904+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:03:43.904+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:03:43.906+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:03:43.905+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 4
    with DAG('ingest_twitter', start_date = datetime(2022,09,30), schedule_interval = '') as dag:
                                                           ^
SyntaxError: invalid token
[2022-10-01T02:03:43.906+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:03:43.919+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.017 seconds
[2022-10-01T02:04:14.025+0000] {processor.py:156} INFO - Started process (PID=4204) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:04:14.026+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:04:14.026+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:04:14.026+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:04:14.027+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:04:14.027+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 4
    with DAG('ingest_twitter', start_date = datetime(2022,09,30), schedule_interval = '') as dag:
                                                           ^
SyntaxError: invalid token
[2022-10-01T02:04:14.027+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:04:14.061+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.037 seconds
[2022-10-01T02:04:36.972+0000] {processor.py:156} INFO - Started process (PID=4257) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:04:36.973+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:04:36.973+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:04:36.973+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:04:36.975+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:04:36.974+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 4
    with DAG('ingest_twitter', start_date = datetime(2022,09,30), schedule_interval = '0 21 * * 0') as dag:
                                                           ^
SyntaxError: invalid token
[2022-10-01T02:04:36.975+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:04:36.987+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.018 seconds
[2022-10-01T02:04:44.096+0000] {processor.py:156} INFO - Started process (PID=4269) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:04:44.097+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:04:44.097+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:04:44.097+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:04:44.098+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:04:44.098+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 4
    with DAG('ingest_twitter', start_date = datetime(2022,09,30), schedule_interval = '0 21 * * 0', catch) as dag:
                                                           ^
SyntaxError: invalid token
[2022-10-01T02:04:44.099+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:04:44.111+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.017 seconds
[2022-10-01T02:04:46.116+0000] {processor.py:156} INFO - Started process (PID=4270) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:04:46.116+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:04:46.116+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:04:46.116+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:04:46.117+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:04:46.117+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 4
    with DAG('ingest_twitter', start_date = datetime(2022,09,30), schedule_interval = '0 21 * * 0', catchup) as dag:
                                                           ^
SyntaxError: invalid token
[2022-10-01T02:04:46.118+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:04:46.130+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.016 seconds
[2022-10-01T02:04:50.145+0000] {processor.py:156} INFO - Started process (PID=4271) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:04:50.145+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:04:50.145+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:04:50.145+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:04:50.147+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:04:50.146+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 4
    with DAG('ingest_twitter', start_date = datetime(2022,09,30), schedule_interval = '0 21 * * 0', catchup = False) as dag:
                                                           ^
SyntaxError: invalid token
[2022-10-01T02:04:50.147+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:04:50.159+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.017 seconds
[2022-10-01T02:05:20.174+0000] {processor.py:156} INFO - Started process (PID=4335) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:05:20.211+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:05:20.212+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:05:20.212+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:05:20.213+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:05:20.212+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 4
    with DAG('ingest_twitter', start_date = datetime(2022,09,30), schedule_interval = '0 21 * * 0', catchup = False) as dag:
                                                           ^
SyntaxError: invalid token
[2022-10-01T02:05:20.214+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:05:20.225+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.053 seconds
[2022-10-01T02:05:27.789+0000] {processor.py:156} INFO - Started process (PID=4379) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:05:27.790+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:05:27.790+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:05:27.790+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:05:27.791+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:05:27.791+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 5
    'ingest_twitter', start_date = datetime(2022,09,30), schedule_interval = '0 21 * * 0', catchup = False) as dag:
                                                  ^
SyntaxError: invalid token
[2022-10-01T02:05:27.792+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:05:27.805+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.018 seconds
[2022-10-01T02:05:29.803+0000] {processor.py:156} INFO - Started process (PID=4380) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:05:29.804+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:05:29.804+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:05:29.804+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:05:29.805+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:05:29.805+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 6
    start_date = datetime(2022,09,30), schedule_interval = '0 21 * * 0', catchup = False) as dag:
                                ^
SyntaxError: invalid token
[2022-10-01T02:05:29.806+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:05:29.818+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.016 seconds
[2022-10-01T02:05:33.838+0000] {processor.py:156} INFO - Started process (PID=4381) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:05:33.838+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:05:33.839+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:05:33.838+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:05:33.840+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:05:33.840+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 6
    start_date = datetime(2022,09,30),
                                ^
SyntaxError: invalid token
[2022-10-01T02:05:33.840+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:05:33.874+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.037 seconds
[2022-10-01T02:05:35.852+0000] {processor.py:156} INFO - Started process (PID=4382) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:05:35.852+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:05:35.853+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:05:35.853+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:05:35.854+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:05:35.853+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 6
    start_date = datetime(2022,09,30),
                                ^
SyntaxError: invalid token
[2022-10-01T02:05:35.854+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:05:35.887+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.037 seconds
[2022-10-01T02:05:38.902+0000] {processor.py:156} INFO - Started process (PID=4392) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:05:38.903+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:05:38.903+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:05:38.903+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:05:38.905+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:05:38.904+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 6
    start_date = datetime(2022,09,30),
                                ^
SyntaxError: invalid token
[2022-10-01T02:05:38.905+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:05:38.948+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.048 seconds
[2022-10-01T02:05:43.022+0000] {processor.py:156} INFO - Started process (PID=4395) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:05:43.022+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:05:43.022+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:05:43.022+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:05:43.024+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:05:43.023+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 8
    catchup = False) as dag:
                           ^
SyntaxError: unexpected EOF while parsing
[2022-10-01T02:05:43.024+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:05:43.036+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.016 seconds
[2022-10-01T02:06:11.905+0000] {processor.py:156} INFO - Started process (PID=4459) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:06:11.943+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:06:11.943+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:06:11.943+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:06:11.944+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:06:11.944+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 9
    catchup = False) as dag:
                           ^
SyntaxError: unexpected EOF while parsing
[2022-10-01T02:06:11.945+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:06:11.957+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.054 seconds
[2022-10-01T02:06:14.922+0000] {processor.py:156} INFO - Started process (PID=4460) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:06:14.922+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:06:14.923+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:06:14.923+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:06:14.924+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:06:14.923+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 9
    catchup = False) as dag:
                           ^
SyntaxError: unexpected EOF while parsing
[2022-10-01T02:06:14.925+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:06:14.936+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.015 seconds
[2022-10-01T02:06:17.937+0000] {processor.py:156} INFO - Started process (PID=4461) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:06:17.937+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:06:17.937+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:06:17.937+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:06:17.938+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:06:17.938+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 9
    catchup = False) as dag:
                           ^
SyntaxError: unexpected EOF while parsing
[2022-10-01T02:06:17.938+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:06:17.950+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.015 seconds
[2022-10-01T02:06:22.974+0000] {processor.py:156} INFO - Started process (PID=4471) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:06:22.974+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:06:22.975+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:06:22.975+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:06:22.976+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:06:22.976+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 9
    catchup = False) as dag:
                           ^
SyntaxError: unexpected EOF while parsing
[2022-10-01T02:06:22.976+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:06:22.988+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.016 seconds
[2022-10-01T02:06:27.774+0000] {processor.py:156} INFO - Started process (PID=4506) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:06:27.774+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:06:27.774+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:06:27.774+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:06:27.776+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:06:27.775+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 9
    catchup = False) as dag:
                           ^
SyntaxError: unexpected EOF while parsing
[2022-10-01T02:06:27.776+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:06:27.788+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.016 seconds
[2022-10-01T02:06:37.820+0000] {processor.py:156} INFO - Started process (PID=4516) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:06:37.821+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:06:37.821+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:06:37.821+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:06:37.822+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:06:37.822+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 11
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-10-01T02:06:37.823+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:06:37.836+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.017 seconds
[2022-10-01T02:06:45.945+0000] {processor.py:156} INFO - Started process (PID=4528) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:06:45.946+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:06:45.946+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:06:45.946+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:06:45.947+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:06:45.947+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 11
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-10-01T02:06:45.947+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:06:45.959+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.015 seconds
[2022-10-01T02:06:49.968+0000] {processor.py:156} INFO - Started process (PID=4529) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:06:49.968+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:06:49.968+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:06:49.968+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:06:49.969+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:06:49.969+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 12
    PythonOperator
                 ^
IndentationError: expected an indented block
[2022-10-01T02:06:49.970+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:06:49.981+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.015 seconds
[2022-10-01T02:07:20.879+0000] {processor.py:156} INFO - Started process (PID=4593) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:07:20.884+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:07:20.884+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:07:20.884+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:07:20.886+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:07:20.885+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 12
    PythonOperator
                 ^
IndentationError: expected an indented block
[2022-10-01T02:07:20.886+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:07:20.898+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.021 seconds
[2022-10-01T02:07:25.681+0000] {processor.py:156} INFO - Started process (PID=4607) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:07:25.681+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:07:25.681+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:07:25.681+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:07:25.683+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:07:25.682+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 12
    create PythonOperator
         ^
IndentationError: expected an indented block
[2022-10-01T02:07:25.683+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:07:25.695+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.016 seconds
[2022-10-01T02:07:29.707+0000] {processor.py:156} INFO - Started process (PID=4638) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:07:29.707+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:07:29.708+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:07:29.708+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:07:29.709+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:07:29.708+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 12
    create_sparkPythonOperator
                             ^
IndentationError: expected an indented block
[2022-10-01T02:07:29.709+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:07:29.743+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.037 seconds
[2022-10-01T02:07:34.730+0000] {processor.py:156} INFO - Started process (PID=4639) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:07:34.730+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:07:34.730+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:07:34.730+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:07:34.732+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:07:34.731+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 12
    create_spark_client = PythonOperator
                      ^
IndentationError: expected an indented block
[2022-10-01T02:07:34.732+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:07:34.744+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.016 seconds
[2022-10-01T02:07:38.748+0000] {processor.py:156} INFO - Started process (PID=4649) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:07:38.748+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:07:38.749+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:07:38.749+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:07:38.750+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:07:38.750+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 12
    create_spark_client = PythonOperator(
                      ^
IndentationError: expected an indented block
[2022-10-01T02:07:38.751+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:07:38.763+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.017 seconds
[2022-10-01T02:07:43.798+0000] {processor.py:156} INFO - Started process (PID=4652) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:07:43.798+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:07:43.798+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:07:43.798+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:07:43.800+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:07:43.799+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 12
    create_spark_client = PythonOperator(
                      ^
IndentationError: expected an indented block
[2022-10-01T02:07:43.800+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:07:43.812+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.016 seconds
[2022-10-01T02:07:45.810+0000] {processor.py:156} INFO - Started process (PID=4653) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:07:45.810+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:07:45.810+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:07:45.810+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:07:45.812+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:07:45.811+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 12
    create_spark_client = PythonOperator(
                      ^
IndentationError: expected an indented block
[2022-10-01T02:07:45.812+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:07:45.845+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.037 seconds
[2022-10-01T02:07:46.834+0000] {processor.py:156} INFO - Started process (PID=4654) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:07:46.834+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:07:46.834+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:07:46.834+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:07:46.836+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:07:46.835+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 12
    create_spark_client = PythonOperator(
                      ^
IndentationError: expected an indented block
[2022-10-01T02:07:46.836+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:07:46.869+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.037 seconds
[2022-10-01T02:08:17.750+0000] {processor.py:156} INFO - Started process (PID=4718) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:08:17.750+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:08:17.751+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:08:17.750+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:08:17.752+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:08:17.751+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 12
    create_spark_client = PythonOperator(
                      ^
IndentationError: expected an indented block
[2022-10-01T02:08:17.752+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:08:17.764+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.016 seconds
[2022-10-01T02:08:48.520+0000] {processor.py:156} INFO - Started process (PID=4782) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:08:48.521+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:08:48.521+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:08:48.521+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:08:48.522+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:08:48.522+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 12
    create_spark_client = PythonOperator(
                      ^
IndentationError: expected an indented block
[2022-10-01T02:08:48.522+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:08:48.556+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.037 seconds
[2022-10-01T02:09:19.367+0000] {processor.py:156} INFO - Started process (PID=4845) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:09:19.379+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:09:19.379+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:09:19.379+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:09:19.380+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:09:19.380+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 12
    create_spark_client = PythonOperator(
                      ^
IndentationError: expected an indented block
[2022-10-01T02:09:19.381+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:09:19.393+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.028 seconds
[2022-10-01T02:09:49.446+0000] {processor.py:156} INFO - Started process (PID=4900) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:09:49.446+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:09:49.447+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:09:49.447+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:09:49.448+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:09:49.448+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 12
    create_spark_client = PythonOperator(
                      ^
IndentationError: expected an indented block
[2022-10-01T02:09:49.448+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:09:49.460+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.016 seconds
[2022-10-01T02:10:19.529+0000] {processor.py:156} INFO - Started process (PID=4964) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:10:19.530+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:10:19.530+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:10:19.530+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:10:19.531+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:10:19.531+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 12
    create_spark_client = PythonOperator(
                      ^
IndentationError: expected an indented block
[2022-10-01T02:10:19.532+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:10:19.543+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.015 seconds
[2022-10-01T02:10:50.380+0000] {processor.py:156} INFO - Started process (PID=5028) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:10:50.381+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:10:50.381+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:10:50.381+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:10:50.383+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:10:50.382+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 12
    create_spark_client = PythonOperator(
                      ^
IndentationError: expected an indented block
[2022-10-01T02:10:50.383+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:10:50.396+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.017 seconds
[2022-10-01T02:11:21.281+0000] {processor.py:156} INFO - Started process (PID=5092) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:11:21.282+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:11:21.282+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:11:21.282+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:11:21.284+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:11:21.283+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 12
    create_spark_client = PythonOperator(
                      ^
IndentationError: expected an indented block
[2022-10-01T02:11:21.284+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:11:21.295+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.015 seconds
[2022-10-01T02:11:52.115+0000] {processor.py:156} INFO - Started process (PID=5156) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:11:52.115+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:11:52.115+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:11:52.115+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:11:52.116+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:11:52.116+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 12
    create_spark_client = PythonOperator(
                      ^
IndentationError: expected an indented block
[2022-10-01T02:11:52.117+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:11:52.150+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.038 seconds
[2022-10-01T02:12:23.006+0000] {processor.py:156} INFO - Started process (PID=5211) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:12:23.044+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:12:23.044+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:12:23.044+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:12:23.046+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:12:23.045+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 12
    create_spark_client = PythonOperator(
                      ^
IndentationError: expected an indented block
[2022-10-01T02:12:23.046+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:12:23.059+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.054 seconds
[2022-10-01T02:12:53.255+0000] {processor.py:156} INFO - Started process (PID=5275) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:12:53.256+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:12:53.256+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:12:53.256+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:12:53.257+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:12:53.257+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 12
    create_spark_client = PythonOperator(
                      ^
IndentationError: expected an indented block
[2022-10-01T02:12:53.257+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:12:53.270+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.017 seconds
[2022-10-01T02:13:24.059+0000] {processor.py:156} INFO - Started process (PID=5339) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:13:24.060+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:13:24.061+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:13:24.060+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:13:24.062+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:13:24.061+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 12
    create_spark_client = PythonOperator(
                      ^
IndentationError: expected an indented block
[2022-10-01T02:13:24.062+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:13:24.074+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.016 seconds
[2022-10-01T02:13:54.137+0000] {processor.py:156} INFO - Started process (PID=5403) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:13:54.138+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:13:54.138+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:13:54.138+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:13:54.139+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:13:54.139+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 12
    create_spark_client = PythonOperator(
                      ^
IndentationError: expected an indented block
[2022-10-01T02:13:54.140+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:13:54.153+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.017 seconds
[2022-10-01T02:14:00.164+0000] {processor.py:156} INFO - Started process (PID=5404) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:00.165+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:14:00.165+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:14:00.165+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:00.166+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:14:00.166+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 12
    create_spark_client = PythonOperator(
                      ^
IndentationError: expected an indented block
[2022-10-01T02:14:00.167+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:00.178+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.015 seconds
[2022-10-01T02:14:04.281+0000] {processor.py:156} INFO - Started process (PID=5405) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:04.281+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:14:04.282+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:14:04.281+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:04.283+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:14:04.282+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 12
    create_spark_client = PythonOperator(
                      ^
IndentationError: expected an indented block
[2022-10-01T02:14:04.283+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:04.297+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.018 seconds
[2022-10-01T02:14:06.293+0000] {processor.py:156} INFO - Started process (PID=5415) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:06.294+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:14:06.294+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:14:06.294+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:06.295+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:14:06.295+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 12
    create_spark_client = PythonOperator(
                      ^
IndentationError: expected an indented block
[2022-10-01T02:14:06.296+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:06.311+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.019 seconds
[2022-10-01T02:14:08.334+0000] {processor.py:156} INFO - Started process (PID=5433) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:08.334+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:14:08.334+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:14:08.334+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:08.335+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:14:08.335+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 12
    create_spark_client = PythonOperator(
                      ^
IndentationError: expected an indented block
[2022-10-01T02:14:08.336+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:08.347+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.016 seconds
[2022-10-01T02:14:10.097+0000] {processor.py:156} INFO - Started process (PID=5451) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:10.098+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:14:10.098+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:14:10.098+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:10.099+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:14:10.099+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 12
    create_spark_client = PythonOperator(
                      ^
IndentationError: expected an indented block
[2022-10-01T02:14:10.099+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:10.133+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.037 seconds
[2022-10-01T02:14:12.121+0000] {processor.py:156} INFO - Started process (PID=5452) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:12.122+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:14:12.122+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:14:12.122+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:12.123+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:14:12.123+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 12
    create_spark_client = PythonOperator(
                      ^
IndentationError: expected an indented block
[2022-10-01T02:14:12.124+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:12.136+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.016 seconds
[2022-10-01T02:14:16.141+0000] {processor.py:156} INFO - Started process (PID=5462) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:16.141+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:14:16.142+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:14:16.141+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:16.143+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:14:16.142+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 12
    create_spark_client = PythonOperator(
                      ^
IndentationError: expected an indented block
[2022-10-01T02:14:16.143+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:16.177+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.038 seconds
[2022-10-01T02:14:21.178+0000] {processor.py:156} INFO - Started process (PID=5463) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:21.179+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:14:21.179+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:14:21.179+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:21.180+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:14:21.180+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 12
    create_spark_client = PythonOperator(
                      ^
IndentationError: expected an indented block
[2022-10-01T02:14:21.180+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:21.192+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.016 seconds
[2022-10-01T02:14:23.189+0000] {processor.py:156} INFO - Started process (PID=5464) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:23.189+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:14:23.189+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:14:23.189+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:23.190+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:14:23.190+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 12
    create_spark_client = PythonOperator(
                      ^
IndentationError: expected an indented block
[2022-10-01T02:14:23.191+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:23.203+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.016 seconds
[2022-10-01T02:14:25.289+0000] {processor.py:156} INFO - Started process (PID=5467) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:25.290+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:14:25.290+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:14:25.290+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:25.291+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:14:25.291+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 12
    create_spark_client = PythonOperator(
                      ^
IndentationError: expected an indented block
[2022-10-01T02:14:25.291+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:25.325+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.038 seconds
[2022-10-01T02:14:29.318+0000] {processor.py:156} INFO - Started process (PID=5477) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:29.318+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:14:29.319+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:14:29.319+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:29.321+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:14:29.320+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 13
    create_spark_client = PythonOperator(
                      ^
IndentationError: expected an indented block
[2022-10-01T02:14:29.321+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:29.339+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.024 seconds
[2022-10-01T02:14:37.410+0000] {processor.py:156} INFO - Started process (PID=5480) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:37.448+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:14:37.448+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:14:37.448+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:37.449+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:14:37.449+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 6
    def create_spark_client:
                           ^
SyntaxError: invalid syntax
[2022-10-01T02:14:37.449+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:37.461+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.052 seconds
[2022-10-01T02:14:40.098+0000] {processor.py:156} INFO - Started process (PID=5523) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:40.099+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:14:40.099+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:14:40.099+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:40.100+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:14:40.100+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 6
    def create_spark_client:
                           ^
SyntaxError: invalid syntax
[2022-10-01T02:14:40.100+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:40.112+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.015 seconds
[2022-10-01T02:14:43.126+0000] {processor.py:156} INFO - Started process (PID=5524) to work on /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:43.126+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/twitter/twitter.ingest_tweets.py for tasks to queue
[2022-10-01T02:14:43.127+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:14:43.127+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:43.128+0000] {logging_mixin.py:117} INFO - [2022-10-01T02:14:43.127+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/twitter/twitter.ingest_tweets.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/twitter/twitter.ingest_tweets.py", line 6
    def create_spark_client:
                           ^
SyntaxError: invalid syntax
[2022-10-01T02:14:43.129+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/twitter/twitter.ingest_tweets.py
[2022-10-01T02:14:43.141+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/twitter/twitter.ingest_tweets.py took 0.017 seconds
